name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $USER -p $PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag antiloquax/comment2:new1
    - name: Docker push
      run: docker push antiloquax/comment2:new1
      
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Contensis block push action
      uses: contensis/block-push@v1
      with:
        block-id: comment
        alias: chesheast
        project-id: blockstest
        image-uri: "antiloquax/comment2:new1 "
        client-id: ${{ secrets.Z_CLIENT_ID }}
        shared-secret: ${{ secrets.Z_SHARED_SECRET }}
        git-token: ${{ secrets.GIT_TOKEN }}
