name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      block-id:
        default: "comment"
        type: string
      auto-release:
        default: false
        type: boolean
      image-uri:
        default: "antiloquax/comment:latest"
        type: string
      alias:
        default: "chesheast"
        type: string
      project-id:
        default: "blockstest"
        type: string
      tag-repo:
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        docker login -u $USER -p $PASS
    
    - name: Build the Docker image
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ROOT_URL: ${{ secrets.ROOT_URL }}
      run: docker build . --file Dockerfile --tag antiloquax/comment:latest --build-arg var_name=${ROOT_URL} --build-arg var_name=${CLIENT_ID} --build-arg var_name=${CLIENT_SECRET}
    - name: Docker push
      run: docker push antiloquax/comment:latest
      
  job2:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Push block to ${{ inputs.project-id }} on ${{ inputs.alias }}
      uses: contensis/block-push@v1
      with:
        block-id: ${{ inputs.block-id }}
        auto-release: ${{ inputs.auto-release }}
        alias: ${{ inputs.alias }}
        image-uri: ${{ inputs.image-uri }}
        project-id: ${{ inputs.project-id }}     
        client-id: ${{ secrets.Z_CLIENT_ID }}
        shared-secret: ${{ secrets.Z_SHARED_SECRET }}
        git-token: ${{ secrets.GIT_TOKEN }}
